version: '3'
services:
  app:
    image: linqbin/linqbin-backend:latest
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - /app/data
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - /data/db
