version: '3'
services:
  app:
    image: linqbin/linqbin-backend:latest
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DB_PG_URL: ${DB_PG_URL}
      DB_PG_USER: ${DB_PG_USER}
      DB_PG_PASSWORD: ${DB_PG_PASSWORD}
    volumes:
      - /app/data
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_PG_USER}
      POSTGRES_PASSWORD: ${DB_PG_PASSWORD}
      POSTGRES_DB: linqbin
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
