version: '3'
services:
  app:
    image: linqbin/linqbin-backend:latest
    env_file:
      - .env
    volumes:
      - /app/data
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - /data/db
